### ISSUE TITLE
Problem with the Weather Underground's array

### ISSUE THREAD

**Issue by GionaFossati** [GionaFossati/WeatherCompare#1]
I can't find the way to display the date and max/min temperature forecast in Weather Underground's array.
The array is named $previsioni_data1 in php/weatherunderground.php

The code i wrote doesn't work:
` echo $previsioni_data1 ['forecast']['txt_forecast']['forecastday']['0']['date']['pretty'];
echo $previsioni_data1 ['forecast']['txt_forecast']['simpleforecast']['high']['celsius'];`

and the error:

> Notice: Undefined index: date in C:\xampp\htdocs\Progetto Informatica\WeatherCompare\php\weatherunderground.php on line 22

I know that probably I made a mistake calling the index, but I can't find the error.

**Comment by andrealeone** [comment]
Got the solution!
Printing the JSON inside the console, this is the result:
<img width="710" alt="stuff" src="https://cloud.githubusercontent.com/assets/16899766/24810787/de6cafa6-1bc3-11e7-8f1a-07cd4c939010.png">
inside `'forecastday'['0']` there is no `['date']` value to retrieve — here's the error.

**Comment by GionaFossati** [comment]
How can I print the JSON in the console?
